# 5. Topic Modeling

In [71]:
import pandas as pd
import gensim
from gensim.utils import simple_preprocess
from gensim import corpora, models
from pprint import pprint
from gensim.models import CoherenceModel
from sklearn.decomposition import NMF
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
import pickle
import re

In [2]:
# loading dataframe with text that has been preprocessed 
Text=pd.read_pickle('processedtext')


In [63]:
lrtf = pickle.load(open("lrtf.pickle", "rb"))
Tfidfvector = pickle.load(open("Tfidfvector.pickle", "rb"))

# LDA

In [161]:
dictionary=gensim.corpora.Dictionary(Text['text'])

corpus=[dictionary.doc2bow(reviews) for reviews in Text['text']]
tfidf = models.TfidfModel(corpus)
corpus_tfidf = tfidf[corpus]


### LDA with 3 topics

In [ ]:
lda_model_tfidf = gensim.models.LdaMulticore(corpus_tfidf, num_topics=3, id2word=dictionary, passes=2, workers=4

In [163]:

for idx, topic in lda_model_tfidf.print_topics(-1):
    print('Topic: {} Word: {}'.format(idx, topic))

Topic: 0 Word: 0.005*"burger" + 0.004*"great" + 0.003*"place" + 0.003*"sandwich" + 0.003*"good" + 0.003*"chicken" + 0.003*"coffee" + 0.003*"love" + 0.003*"friendly" + 0.003*"fry"
Topic: 1 Word: 0.004*"great" + 0.004*"ramen" + 0.003*"dish" + 0.003*"delicious" + 0.003*"good" + 0.003*"amazing" + 0.003*"restaurant" + 0.003*"service" + 0.003*"food" + 0.003*"taco"
Topic: 2 Word: 0.004*"sushi" + 0.003*"food" + 0.003*"order" + 0.003*"u" + 0.003*"time" + 0.003*"thai" + 0.003*"place" + 0.003*"service" + 0.003*"roll" + 0.003*"restaurant"


In [165]:
l=[]
for idx, topic in lda_model_tfidf.print_topics(-1):
    l.append(re.sub('["+0-9.*]','',topic).split('  '))
print('sentiment of topics above')
list(lrtf.predict(Tfidfvector.transform(l)))


sentiment of topics above


[True, True, False]

### LDA with 7 topics

In [166]:
lda_model_tfidf7 = gensim.models.LdaMulticore(corpus_tfidf, num_topics=7, id2word=dictionary, passes=2, workers=4)


In [167]:

for idx, topic in lda_model_tfidf7.print_topics(-1):
    print('Topic: {} Word: {}'.format(idx, topic))

Topic: 0 Word: 0.003*"blaze" + 0.003*"durian" + 0.002*"manic" + 0.002*"nom" + 0.002*"arcade" + 0.001*"cactus" + 0.001*"bbt" + 0.001*"swordfish" + 0.001*"marche" + 0.001*"harvest"
Topic: 1 Word: 0.003*"maha" + 0.003*"porchetta" + 0.002*"cat" + 0.002*"chana" + 0.002*"donair" + 0.001*"daal" + 0.001*"macaron" + 0.001*"rasta" + 0.001*"bi" + 0.001*"puri"
Topic: 2 Word: 0.017*"thai" + 0.017*"ramen" + 0.016*"noodle" + 0.011*"pho" + 0.010*"pad" + 0.009*"dumpling" + 0.008*"broth" + 0.008*"sum" + 0.007*"dim" + 0.007*"soup"
Topic: 3 Word: 0.004*"great" + 0.004*"good" + 0.003*"place" + 0.003*"food" + 0.003*"delicious" + 0.003*"really" + 0.003*"amazing" + 0.003*"chicken" + 0.003*"nice" + 0.003*"service"
Topic: 4 Word: 0.004*"u" + 0.004*"food" + 0.003*"order" + 0.003*"time" + 0.003*"service" + 0.003*"table" + 0.003*"minute" + 0.003*"even" + 0.003*"restaurant" + 0.003*"place"
Topic: 5 Word: 0.016*"sushi" + 0.008*"roll" + 0.006*"sashimi" + 0.005*"japanese" + 0.005*"salmon" + 0.004*"price" + 0.004*"good

In [169]:
l=[]
for idx, topic in lda_model_tfidf7.print_topics(-1):
    l.append(re.sub('["+0-9.*]','',topic).split('  '))
print('sentiment of topics above')
list(lrtf.predict(Tfidfvector.transform(l)))


sentiment of topics above


[False, False, True, True, False, True, False]

# NMF

In [170]:
Tfidfvector=TfidfVectorizer(tokenizer=dummy,preprocessor=dummy,min_df=0.01, max_features=500)
Tfidfvector.fit(Text['text'])
Tfidf=Tfidfvector.transform(Text['text'])

C:\Users\frede\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:507: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"


In [171]:
Tfidfvectorp=TfidfVectorizer(tokenizer=dummy,preprocessor=dummy,min_df=0.01, max_features=500)
Tfidfvectorp.fit(Positive['text'])
Tfidfp=Tfidfvectorp.transform(Positive['text'])

C:\Users\frede\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:507: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"


In [172]:
Tfidfvectorn=TfidfVectorizer(tokenizer=dummy,preprocessor=dummy,min_df=0.01, max_features=500)
Tfidfvectorn.fit(Negetive['text'])
Tfidfn=Tfidfvectorn.transform(Negetive['text'])

C:\Users\frede\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:507: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"


In [173]:
def print_top_words(model, feature,n):
    
    for topic_idx, topic in enumerate(model.components_):
        message = "Topic #%d: " % topic_idx
        message += " ".join([feature[i] for i in topic.argsort()[:-n - 1:-1]])
        print(message)

In [174]:
def listtopics(model, feature,n):
    df=[]
    for topic_idx, topic in enumerate(model.components_):
        
        word = [feature[i] for i in topic.argsort()[:-n - 1:-1]]
       
        df.append(word)
    return df

### NMF with 3 topics

In [175]:
nmf = NMF(n_components=3, random_state=1,
          alpha=.1, l1_ratio=.5).fit(Tfidf)

In [176]:
print("\nTopics in NMF model (Frobenius norm):")
tfidf_feature_names = Tfidfvector.get_feature_names()
print_top_words(nmf,tfidf_feature_names,20)


Topics in NMF model (Frobenius norm):
Topic #0: u time table food order one restaurant would server came get even like back friend drink minute wait service go
Topic #1: great food place service good friendly amazing staff love atmosphere always price delicious nice excellent recommend best definitely go really
Topic #2: chicken good sauce dish burger rice like really also fried soup beef pork salad fry meat place noodle delicious spicy


In [177]:
print('sentiment of topics above')
lrtf.predict(Tfidfvector.transform(listtopics(nmf,tfidf_feature_names,20)))

sentiment of topics above


array([False,  True,  True])

### NMF with 7 topics

In [178]:
nmf7 = NMF(n_components=7, random_state=1,
          alpha=.1, l1_ratio=.5).fit(Tfidf)

In [179]:
print("\nTopics in NMF model (Frobenius norm):")
tfidf_feature_names = Tfidfvector.get_feature_names()
print_top_words(nmf7,tfidf_feature_names,20)


Topics in NMF model (Frobenius norm):
Topic #0: u table time order restaurant food came server would service minute one back ordered even friend asked got experience went
Topic #1: great food service friendly amazing atmosphere staff delicious excellent recommend price definitely restaurant good nice highly back fantastic selection spot
Topic #2: chicken sauce dish rice fried noodle soup beef pork spicy ordered delicious thai salad curry meat also good flavour side
Topic #3: burger fry cheese bun onion poutine juicy topping bacon joint meat beer best good side beef got fresh ordered cooked
Topic #4: pizza pasta topping slice cheese italian sauce tomato fresh delicious ordered salad best mushroom ingredient order good like location one
Topic #5: sushi roll sashimi fresh salmon fish quality lunch price japanese rice restaurant tuna piece place spicy soup chef best eat
Topic #6: place good really love like go ive get always best one time coffee im nice toronto pretty make also try


In [180]:
print('sentiment of topics above')
lrtf.predict(Tfidfvector.transform(DFtopics(nmf7,tfidf_feature_names,20)))

sentiment of topics above


array([False,  True,  True,  True, False,  True,  True])

### Topic modeling on Cora

In [181]:
Rest1=Text[Text['business_id']==Text['business_id'][10000]]

In [182]:
TfidfvectorRest1=TfidfVectorizer(tokenizer=dummy,preprocessor=dummy, min_df=0.01,max_features=500)
TfidfvectorRest1.fit(Rest1['text'])
TfidfRest1=Tfidfvectorn.transform(Rest1['text'])

C:\Users\frede\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:507: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"


In [183]:
nmfRest1 = NMF(n_components=3, random_state=1,
          alpha=.1, l1_ratio=.5).fit(TfidfRest1)

tfidf_feature_namesRest1 = TfidfvectorRest1.get_feature_names()
print_top_words(nmfRest1,tfidf_feature_namesRest1,20)

Topic #0: blue point getting long gave note trying fill favourite meal color price enjoyed reasonable extra two leave also must fantastic
Topic #1: left boyfriend waffle getting favourite today trying gave amazing small take reasonable little french point meal thought downtown weekday unless
Topic #2: downtown atmosphere fill probably completely damn level story managed green complaint cut color ate overall filled others especially flip sure


In [184]:
print('sentiment of topics above')
lrtf.predict(Tfidfvector.transform(DFtopics(nmfRest1,tfidf_feature_namesRest1,20)))

sentiment of topics above


array([False, False, False])

### Topic modeling on Momofuku Noodle Bar 

In [185]:
Rest2=Text[Text['business_id']==Text['business_id'][50000]]

In [186]:
TfidfvectorRest2=TfidfVectorizer(tokenizer=dummy,preprocessor=dummy, min_df=0.01,max_features=500)
TfidfvectorRest2.fit(Rest2['text'])
TfidfRest2=Tfidfvectorn.transform(Rest2['text'])
nmfRest2 = NMF(n_components=3, random_state=1,
          alpha=.1, l1_ratio=.5).fit(TfidfRest2)

tfidf_feature_namesRest2 = TfidfvectorRest2.get_feature_names()
print_top_words(nmfRest2,tfidf_feature_namesRest2,20)

C:\Users\frede\Anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:507: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn("The parameter 'token_pattern' will not be used"


Topic #0: rating bun point pickled bland going entire great better twice coming staff price let reason wrong year type simply fusion
Topic #1: name baos start egg coming reason going let type bland rice great flavorful twice nyc took year mean disappointing pickled
Topic #2: cake point coming disappointing going seemed chang great already entire always disappointed salt start flake mushroom bun bit let found


In [187]:
print('sentiment of topics above')
lrtf.predict(Tfidfvector.transform(DFtopics(nmfRest2,tfidf_feature_namesRest2,20)))

sentiment of topics above


array([False,  True, False])